{% set name = "libipld" %}
{% set version = "3.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/libipld-{{ version }}.tar.gz
  sha256: 7e85ccd9136110e63943d95232b193c893e369c406273d235160e5cc4b39c9ce

build:
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.2,<2.0                     # [build_platform != target_platform]
  host:
    - python
    - maturin >=1.2,<2.0
    - pip
  run:
    - python

test:
  imports:
    - libipld
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/libipld/
  summary: Python binding to the Rust IPLD library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - akrherz
